"""Add foreign key to settings table

Revision ID: 353157019734
Revises: fe8c3421ab44
Create Date: 2024-12-23 20:49:52.175321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353157019734'
down_revision = 'fe8c3421ab44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
