"""Fixed backref conflict

Revision ID: 50582ad1378b
Revises: fe9f22a5b0d4
Create Date: 2024-12-26 22:38:32.580216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50582ad1378b'
down_revision = 'fe9f22a5b0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
