"""Add category_id to Budget model

Revision ID: 514c10cf3ab9
Revises: 6c82504d3ec2
Create Date: 2024-12-23 17:02:00.070959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '514c10cf3ab9'
down_revision = '6c82504d3ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment')
    op.drop_table('expense')
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_constraint('fk_analysis_record', type_='foreignkey')
        batch_op.drop_column('record_id')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index('idx_category_id')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint('fk_analysis', type_='foreignkey')
        batch_op.drop_constraint('fk_budget', type_='foreignkey')
        batch_op.drop_constraint('fk_account', type_='foreignkey')
        batch_op.drop_column('budget_id')
        batch_op.drop_column('account_id')
        batch_op.drop_column('analysis_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('budget_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_account', 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key('fk_budget', 'budget', ['budget_id'], ['id'])
        batch_op.create_foreign_key('fk_analysis', 'analysis', ['analysis_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_index('idx_category_id', ['category_id'], unique=False)

    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_analysis_record', 'records', ['record_id'], ['id'])

    op.create_table('expense',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='expense_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('investment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount_invested', mysql.FLOAT(), nullable=False),
    sa.Column('current_value', mysql.FLOAT(), nullable=False),
    sa.Column('investment_type', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='investment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
