"""Added description to Record model

Revision ID: 594097403cb8
Revises: 50582ad1378b
Create Date: 2024-12-26 23:37:31.159411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594097403cb8'
down_revision = '50582ad1378b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
