"""Rename type to category_type in Record

Revision ID: fe9f22a5b0d4
Revises: 22050fa91617
Create Date: 2024-12-24 15:17:25.536098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe9f22a5b0d4'
down_revision = '22050fa91617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.drop_column('category_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
